MODULE MPL_ALLOCATE_MOD

USE EC_PARKIND, ONLY : JPIM, JPIB, JPRM, JPRD
USE ISO_C_BINDING, ONLY : C_PTR, C_SIZE_T, C_LOC, C_F_POINTER, C_ASSOCIATED, C_NULL_PTR

IMPLICIT NONE

#:set ranks = list (range (1,6))
#:set types = ['INTEGER', 'INTEGER', 'REAL', 'REAL']
#:set kinds = ['IM', 'IB', 'RM', 'RD']

INTERFACE MPL_ALLOCATE
#:for rank in ranks
#:for type, kind in zip (types, kinds)
MODULE PROCEDURE MPL_ALLOCATE_${rank}$${kind}$
#:endfor
#:endfor
END INTERFACE

INTERFACE MPL_DEALLOCATE
#:for rank in ranks
#:for type, kind in zip (types, kinds)
MODULE PROCEDURE MPL_DEALLOCATE_${rank}$${kind}$
#:endfor
#:endfor
END INTERFACE

PRIVATE

TYPE (C_PTR), SAVE :: MPL_ALLOCATE_HEAP = C_NULL_PTR

PUBLIC :: MPL_ALLOCATE, MPL_DEALLOCATE, MPL_ALLOCATE_INIT

#include "fiat_heap.inc"

CONTAINS

SUBROUTINE MPL_ALLOCATE_INIT (SIZE)

INTEGER (KIND=C_SIZE_T), INTENT (IN) :: SIZE

LOGICAL, SAVE :: LLDONE = .FALSE.

IF (.NOT. LLDONE) THEN

  CALL FIAT_HEAP_NEW (MPL_ALLOCATE_HEAP, SIZE)
  LLDONE = .TRUE.

ENDIF

END SUBROUTINE MPL_ALLOCATE_INIT

#:for rank in ranks
#:for type, kind in zip (types, kinds)

#:set suffix = str (rank) + kind

SUBROUTINE MPL_ALLOCATE_${suffix}$ (P, UBOUNDS, LBOUNDS)

${type}$ (KIND=JP${kind}$), POINTER :: P (${ ','.join ([':'] * rank) }$)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (${rank}$)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (${rank}$)

INTEGER (KIND=JPIM) :: ILBOUNDS (${rank}$)
TYPE (C_PTR) :: PTR
INTEGER (KIND=C_SIZE_T) :: ISIZE

ILBOUNDS = 1

IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

IF (.NOT. C_ASSOCIATED (MPL_ALLOCATE_HEAP)) THEN
  ALLOCATE (P (${','.join (map (lambda i: "ILBOUNDS(" + str (i) + "):UBOUNDS (" + str (i) + ")", range (1, rank+1)))}$))
  RETURN
ENDIF

ISIZE = INT (KIND (P), C_SIZE_T)
#:for i in range (1, rank+1, 1)
ISIZE = ISIZE * INT (UBOUNDS(${i}$)-ILBOUNDS(${i}$)+1, C_SIZE_T)
#:endfor

CALL FIAT_HEAP_ALLOCATE (MPL_ALLOCATE_HEAP, ISIZE, PTR)

CALL C_F_POINTER (PTR, P, UBOUNDS-ILBOUNDS+1)

P (${ ', '.join (map (lambda i: 'ILBOUNDS (' + str (i) + '):', range (1, rank+1))) }$) => P

END SUBROUTINE MPL_ALLOCATE_${suffix}$

SUBROUTINE MPL_DEALLOCATE_${suffix}$ (P)

${type}$ (KIND=JP${kind}$), POINTER :: P (${ ','.join ([':'] * rank) }$)

TYPE (C_PTR) :: PTR

IF (.NOT. C_ASSOCIATED (MPL_ALLOCATE_HEAP)) THEN
  DEALLOCATE (P)
  P => NULL ()
  RETURN
ENDIF

PTR = C_LOC (P (${ ', '.join (map (lambda i: 'LBOUND (P, ' + str (i) + ')', range (1, rank+1))) }$))

CALL FIAT_HEAP_DEALLOCATE (MPL_ALLOCATE_HEAP, PTR)

P => NULL ()

END SUBROUTINE MPL_DEALLOCATE_${suffix}$

#:endfor
#:endfor

END MODULE MPL_ALLOCATE_MOD
